### PR TITLE
Tests cleanup, configuration, helpers, and readme

### PR DESCRIPTION
**Pull request by pjanik**
The most important changes:

- repo cleanup (removed node modules from git, and some fixtures with user credentials)
- LARA-specific Cypress helpers
- custom configuration plugin, and configuration pattern
- loading of activities using fixtures
- examples of tests
- readme

I think the most important thing would be to take a look at readme and example tests in `cypress/integration/runtime`, as that should cover all these things in practice. Everything I wrote in Readme is just my proposal. Feel free to suggest something else or let me know if you feel it might not work too well for us. I guess we should move this repo to LARA soon.

@scytacki, @knowuh, @eireland, @kevinsantos-cc, I guess you might be interested at least in [README](https://github.com/concord-consortium/lara-cypress-tests/tree/161289238-tweaks-config). Not asking everyone for a proper review. But I put some opinionated recommendations there, so it would be good if people who are going to use it the most took a look at it. :)

Note that it won't work with current LARA version. Some of these changes depend on this PR: https://github.com/concord-consortium/lara/pull/349
So, the only way to test it is to use local setup and check out `161289238-api-improvements` branch in LARA.

### CODE REVIEW

**Comment by scytacki** [comment]
This is great!

Do you have any information about speed? I'd guess that importing and delete activities on each test could make them slow.

**Comment by scytacki** [comment]
Did you look at the alias stuff in cypress at all? 
I wonder if we could use a pattern like:
`cy.importMaterial("activities/test-activity.json").as('activityUrl')`

then
`cy.visit('@activityUrl')`
or
`cy.deleteMaterial('@activityUrl')`

**Comment by scytacki** [comment]
Looks like they can only be used on dom elements, routes, and direct fixtures.

**Comment by pjanik** [comment]
> Do you have any information about speed? I'd guess that importing and delete activities on each test could make them slow.

Right, although that's implemented using requests without UI. So, it shouldn't be that bad. Or at least it's as fast as it can be if we want to import and export. And I think we do, e.g. to make sure that there's never any run associated with given activity. It could make tests non-deterministc.

It could be a bit faster if there's a way to obtain CSRF token without loading a page. I guess the slowest thing is at the moment is login, as that's done using UI and navigating through UI takes time. We could definitely try to improve it. I just had to stop somewhere.

**Review by knowuh — APPROVED** [review]
I finally got around to looking at this.  Thank you @pjanik – I think it looks really good.

Did we decide not to move this to the LARA Repo?

**Comment by pjanik** [comment]
@knowuh, I opened PR here so changes are more visible. Once we merge LARA API PR, I'll just move it to LARA. I'm assuming that this is ready to be merged.

**Pull request merged**
